/**
 * BinIQ — Notification Service
 * ─────────────────────────────────────────────────────────────────────────────
 * Persistent, client-side notification store backed by localStorage.
 * Survives page refresh. Notifications are generated by reportService
 * whenever a report status changes.
 *
 * Notification shape:
 * {
 *   id:        string     — unique ID
 *   type:      'info' | 'success' | 'warning' | 'danger'
 *   title:     string     — short headline
 *   body:      string     — detail text
 *   reportId:  string     — links to the related report (optional)
 *   status:    string     — the report status that triggered this (optional)
 *   read:      boolean    — has the user seen this?
 *   createdAt: string     — ISO 8601
 * }
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { notificationsApi } from './api'

const NOTIFICATIONS_KEY = 'biniq_notifications_v1'
const MAX_NOTIFICATIONS  = 50   // prune oldest when exceeded

// ── Storage helpers ───────────────────────────────────────────────────────────
export function getNotifications() {
  try {
    return JSON.parse(localStorage.getItem(NOTIFICATIONS_KEY) || '[]')
  } catch {
    return []
  }
}

function saveNotifications(notifications) {
  localStorage.setItem(NOTIFICATIONS_KEY, JSON.stringify(notifications))
}

// ── PUBLIC: Fetch notifications from API with local cache fallback ────────────
export async function fetchNotifications() {
  try {
    const res = await notificationsApi.list()
    const apiNotifs = res.notifications || []
    saveNotifications(apiNotifs)
    return apiNotifs
  } catch (err) {
    return getNotifications()
  }
}

// ── PUBLIC: Add a notification ────────────────────────────────────────────────
/**
 * @param {{ type, title, body, reportId?, status? }} payload
 * @returns {string} The new notification id
 */
export function addNotification(payload) {
  const id  = `notif-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
  const notif = {
    id,
    type:      payload.type     || 'info',
    title:     payload.title    || 'Update',
    body:      payload.body     || '',
    reportId:  payload.reportId || null,
    status:    payload.status   || null,
    read:      false,
    createdAt: new Date().toISOString(),
  }

  let all = getNotifications()
  // Deduplicate: don't add an identical (reportId + status) notification
  // within a 60-second window — prevents repeated triggers from re-renders
  if (notif.reportId && notif.status) {
    const window60s = Date.now() - 60_000
    const isDuplicate = all.some(n =>
      n.reportId === notif.reportId &&
      n.status   === notif.status   &&
      new Date(n.createdAt).getTime() > window60s
    )
    if (isDuplicate) return null
  }

  all = [notif, ...all]
  // Prune oldest beyond MAX
  if (all.length > MAX_NOTIFICATIONS) all = all.slice(0, MAX_NOTIFICATIONS)
  saveNotifications(all)
  return id
}

// ── PUBLIC: Mark one notification as read ────────────────────────────────────
export function markRead(id) {
  const all = getNotifications().map(n =>
    n.id === id ? { ...n, read: true } : n
  )
  saveNotifications(all)
  notificationsApi.markRead(id).catch(() => {})
}

// ── PUBLIC: Mark all notifications as read ────────────────────────────────────
export function markAllRead() {
  const all = getNotifications().map(n => ({ ...n, read: true }))
  saveNotifications(all)
  notificationsApi.markAllRead().catch(() => {})
}

// ── PUBLIC: Delete a notification ────────────────────────────────────────────
export function deleteNotification(id) {
  saveNotifications(getNotifications().filter(n => n.id !== id))
  notificationsApi.delete(id).catch(() => {})
}

// ── PUBLIC: Clear all notifications ──────────────────────────────────────────
export function clearAllNotifications() {
  saveNotifications([])
  notificationsApi.clearAll().catch(() => {})
}

// ── PUBLIC: Unread count ──────────────────────────────────────────────────────
export function getUnreadCount() {
  return getNotifications().filter(n => !n.read).length
}

